### ISSUE TITLE
Adding helper functions into stacks/something.rb files

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn-parameters#12]
Hey Chris

Not an issue but a question. We're using Ruby stack files extensively via this callback and I'd like to add helper functions into the class so we could do something like:

```
Configuration.new do
  template 'some_template'
  parameters do
    elb_subnets get_subnet_list(:live_environment, :public)
  end
end
```

The use case for this is various historical AWS resources are not CloudFormation'd but easily discoverable via the AWS APIs and tags. I'd like our developers to more easily self-serve and use the generic templates without having to deal with resource ID discovery (older, non-CF managed resources like VPCs mean we can't use --apply-stack).

The implementation for the helpers we're thinking about is pretty straight forward, I'm just not sure where to put them to make the methods available in the configuration block above. Any pointers?

Thanks

Jim

**Comment by webframp** [comment]
@jimcroft This is a pretty simple case where I do something like that: https://github.com/webframp/sfn-vault/blob/develop/lib/sfn-vault/inject.rb

I'm sure @chrisroberts can add better details on the right way to do it

**Comment by chrisroberts** [comment]
@jimcroft What @webframp linked to is very close to what you would want, just slightly different since you're looking to add helpers into the configuration builder rather than into the templates. You can build your helpers as a gem, but for simplicity I'll just use a local file. Create a local file with the helper methods defined:

```ruby
# ./configuration_helpers.rb
require 'bogo-config'
module ConfigurationHelpers
  # Custom subnet helper
  def get_subnet_list(*args)
    # do stuff
    :return_value
  end

  # Ensure nested structures are Configuration instances
  def _klass
    ::Configuration
  end
end

Configuration.send(:include, ConfigurationHelpers)
```

Then in the `.sfn` file we load the local file to make the helpers available:

```ruby
require './configuration_helpers.rb'

Configuration.new do
  template 'some_template'
  parameters do
    elb_subnets get_subnet_list(:live_environment, :public)
  end
end
```

In terms of usability, with configuration helpers like this the only way for an end user to modify the arguments to the helper methods is to update the configuration file. If the helper methods are provided as template helpers (which is what @webframp's example is doing), you can setup compile time parameters which can be fed to the helper methods. Just something to think about in terms of usability.

If this didn't fully answer your question, please re-open the issue :smile: 

Cheers!

**Comment by jimcroft** [comment]
Thanks @webframp, @chrisroberts . Works a charm! 👍
